// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4olqcV9_k6gI6ydKWcXKyQtgrfS4u12o',
    appId: '1:808345326532:web:04a15692eba45bc3e48a91',
    messagingSenderId: '808345326532',
    projectId: 'touhan-study',
    authDomain: 'touhan-study.firebaseapp.com',
    storageBucket: 'touhan-study.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqg0fq4Q9styJMmXjH7AuuIOD8OhFbSs',
    appId: '1:808345326532:android:70b685f311991a9ce48a91',
    messagingSenderId: '808345326532',
    projectId: 'touhan-study',
    storageBucket: 'touhan-study.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2sssP2SREUmzS20iu16Rbv0HrY1NlZn8',
    appId: '1:808345326532:ios:da0021e4579b0fc7e48a91',
    messagingSenderId: '808345326532',
    projectId: 'touhan-study',
    storageBucket: 'touhan-study.firebasestorage.app',
    iosBundleId: 'com.touhan.study.touhanStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2sssP2SREUmzS20iu16Rbv0HrY1NlZn8',
    appId: '1:808345326532:ios:da0021e4579b0fc7e48a91',
    messagingSenderId: '808345326532',
    projectId: 'touhan-study',
    storageBucket: 'touhan-study.firebasestorage.app',
    iosBundleId: 'com.touhan.study.touhanStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4olqcV9_k6gI6ydKWcXKyQtgrfS4u12o',
    appId: '1:808345326532:web:692ef49b38595950e48a91',
    messagingSenderId: '808345326532',
    projectId: 'touhan-study',
    authDomain: 'touhan-study.firebaseapp.com',
    storageBucket: 'touhan-study.firebasestorage.app',
  );
}
